### ISSUE TITLE
SkCanvas.createFromImage comes out premultiplied 

### ISSUE THREAD

**Issue by vorg** [deanm/plask#37]
Any chance / option / flag to disable that? I'm trying to encode some data in PNG.

Below picture comparing Plask to WebGL.

![img_7094](https://cloud.githubusercontent.com/assets/171001/6430765/7fa7f8ee-c031-11e4-8e9c-34f3aff4a6b8.JPG)

**Comment by vorg** [comment]
Hi after more tests with `save-pixels` and `get-pixels` from npm, looks like the premultiplications happens on save?

Digging in code looks like you are doing the right thing 

**plask_bindings.mm / writeImage**
```objc
SkImageInfo image_info = canvas->imageInfo()
.makeColorType(kN32_SkColorType)
.makeAlphaType(kUnpremul_SkAlphaType);
```

but..

**SkImageInfo.h** 
```objc
/**
     *  All pixels have their color components stored without any regard to the
     *  alpha. e.g. this is the default configuration for PNG images.
     *
     *  This alpha-type is ONLY supported for input images. Rendering cannot
     *  generate this on output.
     */
    kUnpremul_SkAlphaType,
```
> Rendering cannot generate this on output.

What does it mean?

**Comment by deanm** [comment]
I need to have another look at this, I think I should switch to the PNG encoder in Skia itself.

About alpha, you can't really disabled unpremultiplication, because Skia works premultiplied but PNG doesn't:


http://www.w3.org/TR/PNG-Rationale.html

12.8. Non-premultiplied alpha

PNG uses "unassociated" or "non-premultiplied" alpha so that images with separate transparency masks can be stored losslessly. Another common technique, "premultiplied alpha", stores pixel values premultiplied by the alpha fraction; in effect, the image is already composited against a black background. Any image data hidden by the transparency mask is irretrievably lost by that method, since multiplying by a zero alpha value always produces zero.
Some image rendering techniques generate images with premultiplied alpha (the alpha value actually represents how much of the pixel is covered by the image). This representation can be converted to PNG by dividing the sample values by alpha, except where alpha is zero. The result will look good if displayed by a viewer that handles alpha properly, but will not look very good if the viewer ignores the alpha channel.

Although each form of alpha storage has its advantages, we did not want to require all PNG viewers to handle both forms. We standardized on non-premultiplied alpha as being the lossless and more general case.

**Comment by deanm** [comment]
What is save-pixels from npm?

Anyway, I've checked through the current code, and I think premultiplication is working correctly.  I added a test (what an idea!) in 8484d2fc39d28d40569c78d1f72ba562c3e4b565 and it seems to pass as expected, and I've also manually checked the PNG it produces in Photoshop and it looks right.

If you want to just stick arbitrary data into a PNG with alpha, than Skia is not the right approach, it is a graphics API not a direct data to PNG API.

Do things also look okay from WebGL, or what am I missing?

**Comment by deanm** [comment]
I think I misunderstood your issue.  The answer is no, there isn't a way to read in the data without premultiplication.  If you really need to stash data in a PNG, I would make a PNG without an alpha channel and just put the data in RGB.  Should be able the same size I would think.

**Comment by vorg** [comment]
> If you want to just stick arbitrary data into a PNG with alpha, than Skia is not the right approach,

Right, I see. 

> 12.8 ..Any image data hidden by the transparency mask is irretrievably lost by that method, since multiplying by a zero alpha value always produces zero.

The problem with premultiplied alpha that it breaks linear interpolation of colors if you don't do additive blending. You get black creeping in from the transparent areas.

![screen shot 2015-05-03 at 14 22 44](https://cloud.githubusercontent.com/assets/171001/7445193/f1a79220-f19f-11e4-8f14-f8b32dbe2307.png)

**Comment by deanm** [comment]
How are you blending? gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA) ?

**Comment by vorg** [comment]
Yes, do you think that will be the reason?

**Comment by vorg** [comment]
I think I get it now: Browser on the left vs Plask on the right
![screen shot 2015-05-03 at 20 22 07](https://cloud.githubusercontent.com/assets/171001/7446487/2e45d11a-f1d2-11e4-9977-c70fa5e6b2ab.png)

Changing it to gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA) works everywhere.

**Comment by deanm** [comment]
https://www.khronos.org/registry/webgl/specs/latest/1.0/#2.4

https://www.khronos.org/registry/webgl/specs/latest/1.0/#TEXIMAGE2D_HTML

Some implementations of HTMLCanvasElement's CanvasRenderingContext2D store color values internally in premultiplied form. If such a canvas is uploaded to a WebGL texture with the UNPACK_PREMULTIPLY_ALPHA_WEBGL pixel storage parameter set to false, the color channels will have to be un-multiplied by the alpha channel, which is a lossy operation.

Plask currently doesn't do anything with UNPACK_PREMULTIPLY_ALPHA_WEBGL

It seems like from the WebGL side what you could do is set UNPACK_PREMULTIPLY_ALPHA_WEBGL to true which gives you premultiplied textures, which matches Plask/Skia.

**Comment by deanm** [comment]
If I remember well anyway, all of Chrome at least is working in premultiplied alpha, so if you're not setting UNPACK_PREMULTIPLY_ALPHA_WEBGL to true than you are anyway wasting a bunch of time internally unpremultiplying the textures.  So I think it should be a win everywhere.

I can add code in Plask to make sure it doesn't error when you set UNPACK_PREMULTIPLY_ALPHA_WEBGL so that you can have the same code path in both WebGL and Plask.  The constant is already there I just probably want to check it in pixelStorei and do nothing when you set it to true.

**Comment by deanm** [comment]
https://github.com/deanm/plask/commit/91d3418dfcdfac90b510b52f09a5472f3694ec00
