### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by brainlessboy** [deanm/plask#55]
Hi, i just came across Plask while looking for a method to output graphics from node.js. 
It looks great and seems to work great as well.

- is it still maintained?
- how to i make a full screen window with setFullscreen and getScreenSize().with?
- are there more examples then the basic ones, like more related to Plask ?

cheers,
Oliver

**Comment by deanm** [comment]
I would like for it to still be maintained, but the world on which Plask was built (node, v8, webgl, osx, x86) continually moves extremely fast underneath it. Currently there is a large amount of work to 1) update to the most recent v8 2) update to the most recent node.js 3) support the lastest version of osx (without breaking back compat?). I am not even sure what the status of OpenGL is on modern macs. 4) make a build for M1 ARM macs. There is also probably a 5) which is catch up on updates around the webgl/etc spec evolution.

Happy for anyone to contribute to any of these!

That being said, even the now ancient latest release of Plask should run on modern osx/x86 machines. @vorg is probably the best person to ask, I think the general trend was a lot of people just moved to doing everything in the browser, the browser world is just convenient for a lot of reasons and you don't have to constantly play catchup. At the same time there are a lot of pitfalls, esp w/ regards to convenience, security, and performance, which is why Plask was written. But also Plask was written in the dinosaur age before WebGL was even really a real thing.

**Comment by brainlessboy** [comment]
many thanks for your answer, yes Plask runs on the new M1. How ever, WebGL is here and the browser is convenient, an unescapable fact.
